service: expense-tracker

package:
  exclude:
    - src/**

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2

functions:
  expense-tracker:
    handler: build/src/index.handler
    memorySize: 128
    events:
      - http:
          path: /hello-world
          method: get
          cors: true
